name: babel_text
description: 'A easy and highly customizable "Text" compoent. Change dynamically styles, add intuitively onTap functions in texts, easly display tooltip messages and more!'
version: 2.0.0
repository: https://github.com/Go-Babel/babel_text
issue_tracker: https://github.com/Go-Babel/babel_text/issues
topics: [text, tooltip, style]

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0